allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  deno: true
  esbuild: true
  keytar: true
  prisma: true
  sharp: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - deno
  - esbuild
  - keytar
  - prisma
  - sharp
